import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      // server.ts is the process entrypoint (starts Fastify, binds ports);
      // it is exercised by running the app, not by unit tests.
      // src/generated/prisma/** is Prisma-generated client code, not
      // hand-written source; it is regenerated by `prisma generate` and
      // has no independent logic to unit test.
      // src/runtime/runnerTypes.ts contains only `interface` declarations
      // (no runtime statements) — TypeScript erases `type`-only content on
      // compile, so v8 never observes this file executing and always
      // reports it as 0/0, dragging down the aggregate for no reason.
      exclude: ["src/server.ts", "src/generated/prisma/**", "src/runtime/runnerTypes.ts"],
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "coverage",
    },
  },
});
